### ISSUE TITLE
Error loading module from modules/javax/sql/api/main/module.xml

### ISSUE THREAD

**Issue by aamonten** [wildfly-swarm/wildfly-swarm-examples#21]
Hi, I'm trying to run examples 1.0.0.Alpha5-SNAPSHOT, previously I made a local build of HEAD of wildfly-swarm, when running examples using command:

java -jar target\wildfly-swarm-example-simple-swarm.jar

I get the error:

```
c:\Devzone\wildfly-swarm\wildfly-swarm-examples-master\simple>java -jar target\wildfly-swarm-example-simple-swarm.jar > error.log
org.jboss.modules.ModuleLoadException: Error loading module from modules/javax/sql/api/main/module.xml
        at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
        at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:17)
        at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:35)
        at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
        at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
        at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
        at org.jboss.modules.Module.addExportedPaths(Module.java:1179)
        at org.jboss.modules.Module.addPaths(Module.java:1071)
        at org.jboss.modules.Module.link(Module.java:1398)
        at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
        at org.wildfly.swarm.bootstrap.util.Layout.getBootstrapClassLoader(Layout.java:90)
        at org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder.findModule(ClasspathModuleFinder.java:25)
        at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
        at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
        at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:234)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:49)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:1.1.0.Final' (position: END_TAG seen ...g.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:1.1.0.Final"/>... @27:93)
        at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
        at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
        at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
        at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
        at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
        ... 17 more
org.jboss.modules.ModuleLoadException: Error loading module from modules/javax/sql/api/main/module.xml
        at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
        at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:17)
        at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:35)
        at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
        at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
        at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
        at org.jboss.modules.Module.addExportedPaths(Module.java:1179)
        at org.jboss.modules.Module.addPaths(Module.java:1071)
        at org.jboss.modules.Module.link(Module.java:1398)
        at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:49)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:1.1.0.Final' (position: END_TAG seen ...g.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:1.1.0.Final"/>... @27:93)
        at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
        at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
        at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
        at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
        at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
        ... 11 more
Exception in thread "main" org.jboss.modules.ModuleLoadException: Error loading module from modules/javax/sql/api/main/module.xml
        at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
        at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:17)
        at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:35)
        at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
        at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
        at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
        at org.jboss.modules.Module.addExportedPaths(Module.java:1179)
        at org.jboss.modules.Module.addPaths(Module.java:1071)
        at org.jboss.modules.Module.link(Module.java:1398)
        at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:49)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:1.1.0.Final' (position: END_TAG seen ...g.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:1.1.0.Final"/>... @27:93)
        at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
        at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
        at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
        at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
        at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
        ... 11 more
```

Do you have a recommendation of what I'm missing?

**Comment by kenfinnigan** [comment]
Which JDK are you using? We have a requirement for JDK 8

**Comment by aamonten** [comment]
I'm using:
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

On windows 7 64bits
